
name: Java Maven Cache Demo

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository

          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Application
        run: mvn clean package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-application
          path: target/*.jar
          retention-days: 1
